//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICEpdv
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class siceEntities : DbContext
    {
        public siceEntities()
            : base("name=siceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<comanda> comanda { get; set; }
        public DbSet<consumo> consumo { get; set; }
        public DbSet<consumoitem> consumoitem { get; set; }
        public DbSet<consumoporconta> consumoporconta { get; set; }
        public DbSet<contador> contador { get; set; }
        public DbSet<contpedido> contpedido { get; set; }
        public DbSet<enderecos> enderecos { get; set; }
        public DbSet<mesa> mesa { get; set; }
        public DbSet<orcamentodetail> orcamentodetail { get; set; }
        public DbSet<producaomovmateria> producaomovmateria { get; set; }
        public DbSet<producaomovsetor> producaomovsetor { get; set; }
        public DbSet<producaosetor> producaosetor { get; set; }
        public DbSet<servicodetail> servicodetail { get; set; }
        public DbSet<veiculosclientes> veiculosclientes { get; set; }
        public DbSet<C60a> C60a { get; set; }
        public DbSet<C60m> C60m { get; set; }
        public DbSet<abastecimento> abastecimento { get; set; }
        public DbSet<acerto> acerto { get; set; }
        public DbSet<acessooperadores> acessooperadores { get; set; }
        public DbSet<agenda> agenda { get; set; }
        public DbSet<agenda_contatos> agenda_contatos { get; set; }
        public DbSet<agendacontactos> agendacontactos { get; set; }
        public DbSet<aniversarios> aniversarios { get; set; }
        public DbSet<anuncio> anuncio { get; set; }
        public DbSet<areas> areas { get; set; }
        public DbSet<assistenciaprodutos> assistenciaprodutos { get; set; }
        public DbSet<assistentegerencial> assistentegerencial { get; set; }
        public DbSet<atualizacoes> atualizacoes { get; set; }
        public DbSet<auditoria> auditoria { get; set; }
        public DbSet<bairros> bairros { get; set; }
        public DbSet<balanco> balanco { get; set; }
        public DbSet<bancos> bancos { get; set; }
        public DbSet<banners> banners { get; set; }
        public DbSet<bico> bico { get; set; }
        public DbSet<bombas> bombas { get; set; }
        public DbSet<caixa> caixa { get; set; }
        public DbSet<caixaadm> caixaadm { get; set; }
        public DbSet<caixaarquivo> caixaarquivo { get; set; }
        public DbSet<caixaarquivo_arq> caixaarquivo_arq { get; set; }
        public DbSet<caixadav> caixadav { get; set; }
        public DbSet<caixadavos> caixadavos { get; set; }
        public DbSet<caixanf> caixanf { get; set; }
        public DbSet<caixaprevenda> caixaprevenda { get; set; }
        public DbSet<caixaprevendapaf> caixaprevendapaf { get; set; }
        public DbSet<caixas> caixas { get; set; }
        public DbSet<caixassoma> caixassoma { get; set; }
        public DbSet<caixatmp> caixatmp { get; set; }
        public DbSet<cartoes> cartoes { get; set; }
        public DbSet<cbd001> cbd001 { get; set; }
        public DbSet<cbd001cartoes> cbd001cartoes { get; set; }
        public DbSet<cbd001det> cbd001det { get; set; }
        public DbSet<cbd001detadicoes> cbd001detadicoes { get; set; }
        public DbSet<cbd001detarma> cbd001detarma { get; set; }
        public DbSet<cbd001detcofins> cbd001detcofins { get; set; }
        public DbSet<cbd001detdi> cbd001detdi { get; set; }
        public DbSet<cbd001deticmsnormalst> cbd001deticmsnormalst { get; set; }
        public DbSet<cbd001detipi> cbd001detipi { get; set; }
        public DbSet<cbd001detmed> cbd001detmed { get; set; }
        public DbSet<cbd001detpis> cbd001detpis { get; set; }
        public DbSet<cbd001duplicatas> cbd001duplicatas { get; set; }
        public DbSet<cbd001lacres> cbd001lacres { get; set; }
        public DbSet<cbd001nref> cbd001nref { get; set; }
        public DbSet<cbd001obsfisco> cbd001obsfisco { get; set; }
        public DbSet<cbd001procref> cbd001procref { get; set; }
        public DbSet<cbd001reboque> cbd001reboque { get; set; }
        public DbSet<cbd001vol> cbd001vol { get; set; }
        public DbSet<cedentecheques> cedentecheques { get; set; }
        public DbSet<cedentecontlanc> cedentecontlanc { get; set; }
        public DbSet<cedentefactoring> cedentefactoring { get; set; }
        public DbSet<cfops> cfops { get; set; }
        public DbSet<chamado> chamado { get; set; }
        public DbSet<cheques> cheques { get; set; }
        public DbSet<cidades> cidades { get; set; }
        public DbSet<classe> classe { get; set; }
        public DbSet<classefiscal> classefiscal { get; set; }
        public DbSet<clientes> clientes { get; set; }
        public DbSet<clientesavaliacao> clientesavaliacao { get; set; }
        public DbSet<clientescoordenas> clientescoordenas { get; set; }
        public DbSet<clientesexternos> clientesexternos { get; set; }
        public DbSet<clientesfoto> clientesfoto { get; set; }
        public DbSet<clientesprospects> clientesprospects { get; set; }
        public DbSet<cmsarticles> cmsarticles { get; set; }
        public DbSet<cmsgroups> cmsgroups { get; set; }
        public DbSet<cmssections> cmssections { get; set; }
        public DbSet<cmsusers> cmsusers { get; set; }
        public DbSet<cobradores> cobradores { get; set; }
        public DbSet<cof> cof { get; set; }
        public DbSet<comissao> comissao { get; set; }
        public DbSet<configfinanc> configfinanc { get; set; }
        public DbSet<consultaclientes> consultaclientes { get; set; }
        public DbSet<consumoitem_temp> consumoitem_temp { get; set; }
        public DbSet<contacerto> contacerto { get; set; }
        public DbSet<contactos> contactos { get; set; }
        public DbSet<contador_ajuda> contador_ajuda { get; set; }
        public DbSet<contasbanco> contasbanco { get; set; }
        public DbSet<contaspagar> contaspagar { get; set; }
        public DbSet<contbalanco> contbalanco { get; set; }
        public DbSet<contcaixaadm> contcaixaadm { get; set; }
        public DbSet<contdav> contdav { get; set; }
        public DbSet<contdavos> contdavos { get; set; }
        public DbSet<contdepositocheques> contdepositocheques { get; set; }
        public DbSet<contdevolucao> contdevolucao { get; set; }
        public DbSet<contdocs> contdocs { get; set; }
        public DbSet<contdocs_arq> contdocs_arq { get; set; }
        public DbSet<contdownload> contdownload { get; set; }
        public DbSet<contentradamateriaprima> contentradamateriaprima { get; set; }
        public DbSet<contfinanceiro> contfinanceiro { get; set; }
        public DbSet<continventario> continventario { get; set; }
        public DbSet<contlicitacao> contlicitacao { get; set; }
        public DbSet<contnfsaida> contnfsaida { get; set; }
        public DbSet<contperdas> contperdas { get; set; }
        public DbSet<contpesquisapreco> contpesquisapreco { get; set; }
        public DbSet<contprevendas> contprevendas { get; set; }
        public DbSet<contprevendaspaf> contprevendaspaf { get; set; }
        public DbSet<contproducao> contproducao { get; set; }
        public DbSet<contratos> contratos { get; set; }
        public DbSet<contratosclientes> contratosclientes { get; set; }
        public DbSet<contrecebimento> contrecebimento { get; set; }
        public DbSet<contrelatoriogerencial> contrelatoriogerencial { get; set; }
        public DbSet<contreposicao> contreposicao { get; set; }
        public DbSet<contromaneio> contromaneio { get; set; }
        public DbSet<conttransf> conttransf { get; set; }
        public DbSet<contvencidos> contvencidos { get; set; }
        public DbSet<contvendapadronizada> contvendapadronizada { get; set; }
        public DbSet<crmovclientes> crmovclientes { get; set; }
        public DbSet<crmovclientespagas> crmovclientespagas { get; set; }
        public DbSet<curriculum> curriculum { get; set; }
        public DbSet<curriculumcargos> curriculumcargos { get; set; }
        public DbSet<dbcartoes> dbcartoes { get; set; }
        public DbSet<dbcheques> dbcheques { get; set; }
        public DbSet<dbpagamentos> dbpagamentos { get; set; }
        public DbSet<dependentes> dependentes { get; set; }
        public DbSet<despesas> despesas { get; set; }
        public DbSet<despesasub> despesasub { get; set; }
        public DbSet<devolucao> devolucao { get; set; }
        public DbSet<dicodprodutos> dicodprodutos { get; set; }
        public DbSet<digitalindoor> digitalindoor { get; set; }
        public DbSet<digitalindooraparelho> digitalindooraparelho { get; set; }
        public DbSet<downloads> downloads { get; set; }
        public DbSet<ecf> ecf { get; set; }
        public DbSet<empresa> empresa { get; set; }
        public DbSet<empresas> empresas { get; set; }
        public DbSet<entradagrade> entradagrade { get; set; }
        public DbSet<entradamateriaprima> entradamateriaprima { get; set; }
        public DbSet<entradas> entradas { get; set; }
        public DbSet<erros> erros { get; set; }
        public DbSet<estados> estados { get; set; }
        public DbSet<fabricantes> fabricantes { get; set; }
        public DbSet<filiais> filiais { get; set; }
        public DbSet<financeira> financeira { get; set; }
        public DbSet<fluxocaixa> fluxocaixa { get; set; }
        public DbSet<fornecedores> fornecedores { get; set; }
        public DbSet<funcionarios> funcionarios { get; set; }
        public DbSet<geradordetalhe> geradordetalhe { get; set; }
        public DbSet<geradormaster> geradormaster { get; set; }
        public DbSet<gerenciaservicos> gerenciaservicos { get; set; }
        public DbSet<grade> grade { get; set; }
        public DbSet<grupos> grupos { get; set; }
        public DbSet<ie_st_outrosestados> ie_st_outrosestados { get; set; }
        public DbSet<imobilizados> imobilizados { get; set; }
        public DbSet<imobilizadosgrupo> imobilizadosgrupo { get; set; }
        public DbSet<imobilizadossituacao> imobilizadossituacao { get; set; }
        public DbSet<imobilizadossubgrupo> imobilizadossubgrupo { get; set; }
        public DbSet<infocomplementarnf> infocomplementarnf { get; set; }
        public DbSet<iqsistemas> iqsistemas { get; set; }
        public DbSet<itensaentregar> itensaentregar { get; set; }
        public DbSet<itenspesquisapreco> itenspesquisapreco { get; set; }
        public DbSet<juros> juros { get; set; }
        public DbSet<listanegra> listanegra { get; set; }
        public DbSet<lmccontrole> lmccontrole { get; set; }
        public DbSet<lmcrecebido> lmcrecebido { get; set; }
        public DbSet<lmctanque> lmctanque { get; set; }
        public DbSet<lmcvendas> lmcvendas { get; set; }
        public DbSet<maladireta> maladireta { get; set; }
        public DbSet<marcadorcrmensal> marcadorcrmensal { get; set; }
        public DbSet<mascarafiscal> mascarafiscal { get; set; }
        public DbSet<mdfeide> mdfeide { get; set; }
        public DbSet<mdferodo> mdferodo { get; set; }
        public DbSet<mensagematualizacao> mensagematualizacao { get; set; }
        public DbSet<mensagematualizacaolida> mensagematualizacaolida { get; set; }
        public DbSet<mensagemchat> mensagemchat { get; set; }
        public DbSet<modelos> modelos { get; set; }
        public DbSet<movcartoes> movcartoes { get; set; }
        public DbSet<movcontasbanco> movcontasbanco { get; set; }
        public DbSet<movdespesas> movdespesas { get; set; }
        public DbSet<moventradas> moventradas { get; set; }
        public DbSet<movfuncionarios> movfuncionarios { get; set; }
        public DbSet<movimento> movimento { get; set; }
        public DbSet<movreceitas> movreceitas { get; set; }
        public DbSet<movtransf> movtransf { get; set; }
        public DbSet<n1> n1 { get; set; }
        public DbSet<naturezanf> naturezanf { get; set; }
        public DbSet<nfe012> nfe012 { get; set; }
        public DbSet<nfecontrole> nfecontrole { get; set; }
        public DbSet<nfeinterestadual> nfeinterestadual { get; set; }
        public DbSet<nfoperacao> nfoperacao { get; set; }
        public DbSet<orcamentomaster> orcamentomaster { get; set; }
        public DbSet<orcamentosuporte> orcamentosuporte { get; set; }
        public DbSet<pastadocs> pastadocs { get; set; }
        public DbSet<pedidocompra> pedidocompra { get; set; }
        public DbSet<pedidostmp> pedidostmp { get; set; }
        public DbSet<pendencias> pendencias { get; set; }
        public DbSet<pesquisapreco> pesquisapreco { get; set; }
        public DbSet<posicaoestoque> posicaoestoque { get; set; }
        public DbSet<premios> premios { get; set; }
        public DbSet<prerecebimento> prerecebimento { get; set; }
        public DbSet<processo> processo { get; set; }
        public DbSet<producao> producao { get; set; }
        public DbSet<produtos> produtos { get; set; }
        public DbSet<produtos_iqs> produtos_iqs { get; set; }
        public DbSet<produtoscomposicao> produtoscomposicao { get; set; }
        public DbSet<produtoscustogerencial> produtoscustogerencial { get; set; }
        public DbSet<produtosfilial> produtosfilial { get; set; }
        public DbSet<produtosgrade> produtosgrade { get; set; }
        public DbSet<produtosimagens> produtosimagens { get; set; }
        public DbSet<produtosinventario> produtosinventario { get; set; }
        public DbSet<produtoslicitacao> produtoslicitacao { get; set; }
        public DbSet<produtosmateriaprima> produtosmateriaprima { get; set; }
        public DbSet<produtosperdas> produtosperdas { get; set; }
        public DbSet<produtosretidos> produtosretidos { get; set; }
        public DbSet<produtosvencidos> produtosvencidos { get; set; }
        public DbSet<produtosvencidosubtitutos> produtosvencidosubtitutos { get; set; }
        public DbSet<produtosweb> produtosweb { get; set; }
        public DbSet<profissao> profissao { get; set; }
        public DbSet<projetos> projetos { get; set; }
        public DbSet<projetoshistorico> projetoshistorico { get; set; }
        public DbSet<quantidaderegistros> quantidaderegistros { get; set; }
        public DbSet<r01> r01 { get; set; }
        public DbSet<r02> r02 { get; set; }
        public DbSet<r03> r03 { get; set; }
        public DbSet<receitas> receitas { get; set; }
        public DbSet<receitasub> receitasub { get; set; }
        public DbSet<remessa> remessa { get; set; }
        public DbSet<reposicao> reposicao { get; set; }
        public DbSet<restricoesfiliais> restricoesfiliais { get; set; }
        public DbSet<retornoboleto> retornoboleto { get; set; }
        public DbSet<retornoboleto_fiscal> retornoboleto_fiscal { get; set; }
        public DbSet<retornorecebimento> retornorecebimento { get; set; }
        public DbSet<romaneio> romaneio { get; set; }
        public DbSet<scripts> scripts { get; set; }
        public DbSet<secao> secao { get; set; }
        public DbSet<senhacontrole> senhacontrole { get; set; }
        public DbSet<senhas> senhas { get; set; }
        public DbSet<senhasdefault> senhasdefault { get; set; }
        public DbSet<senhaspadrao> senhaspadrao { get; set; }
        public DbSet<senhatmp> senhatmp { get; set; }
        public DbSet<seqsice> seqsice { get; set; }
        public DbSet<serienf> serienf { get; set; }
        public DbSet<servicocliente> servicocliente { get; set; }
        public DbSet<servicomaster> servicomaster { get; set; }
        public DbSet<servicoporconta> servicoporconta { get; set; }
        public DbSet<servicos> servicos { get; set; }
        public DbSet<servicos_original> servicos_original { get; set; }
        public DbSet<situacaocli> situacaocli { get; set; }
        public DbSet<subgrupos> subgrupos { get; set; }
        public DbSet<subsetorcp> subsetorcp { get; set; }
        public DbSet<sugestao> sugestao { get; set; }
        public DbSet<tab_municipios> tab_municipios { get; set; }
        public DbSet<tabelacest> tabelacest { get; set; }
        public DbSet<tabelacstpiscofins> tabelacstpiscofins { get; set; }
        public DbSet<tabelaibpt> tabelaibpt { get; set; }
        public DbSet<tabelancm> tabelancm { get; set; }
        public DbSet<tabelaservicos> tabelaservicos { get; set; }
        public DbSet<tabelastncm> tabelastncm { get; set; }
        public DbSet<tanque> tanque { get; set; }
        public DbSet<tarefacolaboradores> tarefacolaboradores { get; set; }
        public DbSet<temp> temp { get; set; }
        public DbSet<temp_itensmov> temp_itensmov { get; set; }
        public DbSet<testeimplementacao> testeimplementacao { get; set; }
        public DbSet<tickets> tickets { get; set; }
        public DbSet<tipocliente> tipocliente { get; set; }
        public DbSet<transacoesnfce> transacoesnfce { get; set; }
        public DbSet<transportadoras> transportadoras { get; set; }
        public DbSet<transprd> transprd { get; set; }
        public DbSet<unidademedidas> unidademedidas { get; set; }
        public DbSet<useronline> useronline { get; set; }
        public DbSet<usuariochat> usuariochat { get; set; }
        public DbSet<veiculos> veiculos { get; set; }
        public DbSet<venda> venda { get; set; }
        public DbSet<vendaarquivo> vendaarquivo { get; set; }
        public DbSet<vendadav> vendadav { get; set; }
        public DbSet<vendadavos> vendadavos { get; set; }
        public DbSet<vendaexclusao> vendaexclusao { get; set; }
        public DbSet<vendanf> vendanf { get; set; }
        public DbSet<vendanftmp> vendanftmp { get; set; }
        public DbSet<vendapadronizada> vendapadronizada { get; set; }
        public DbSet<vendaprevenda> vendaprevenda { get; set; }
        public DbSet<vendaprevendapaf> vendaprevendapaf { get; set; }
        public DbSet<vendas> vendas { get; set; }
        public DbSet<vendatmp> vendatmp { get; set; }
        public DbSet<vendedores> vendedores { get; set; }
        public DbSet<versao> versao { get; set; }
        public DbSet<web_casos_sucesso> web_casos_sucesso { get; set; }
        public DbSet<web_downloads> web_downloads { get; set; }
        public DbSet<web_noticias> web_noticias { get; set; }
        public DbSet<web_paginas_genericas> web_paginas_genericas { get; set; }
        public DbSet<web_produtos_atualizacoes> web_produtos_atualizacoes { get; set; }
        public DbSet<web_tutoriais> web_tutoriais { get; set; }
        public DbSet<webservicecontratos> webservicecontratos { get; set; }
        public DbSet<C60d> C60d { get; set; }
        public DbSet<C60i> C60i { get; set; }
        public DbSet<C60r> C60r { get; set; }
        public DbSet<analise_venda_caixa> analise_venda_caixa { get; set; }
        public DbSet<apuracaofiscal> apuracaofiscal { get; set; }
        public DbSet<blococregc190> blococregc190 { get; set; }
        public DbSet<blococregc190_saida> blococregc190_saida { get; set; }
        public DbSet<blococregc300> blococregc300 { get; set; }
        public DbSet<blococregc320> blococregc320 { get; set; }
        public DbSet<blococregc321> blococregc321 { get; set; }
        public DbSet<blococregc381_pis> blococregc381_pis { get; set; }
        public DbSet<blococregc385_cofins> blococregc385_cofins { get; set; }
        public DbSet<blococregc390> blococregc390 { get; set; }
        public DbSet<blococregc400> blococregc400 { get; set; }
        public DbSet<blococregc425> blococregc425 { get; set; }
        public DbSet<blococregc470> blococregc470 { get; set; }
        public DbSet<blococregc470_02_itens> blococregc470_02_itens { get; set; }
        public DbSet<blococregc481_pis> blococregc481_pis { get; set; }
        public DbSet<blococregc485_cofins> blococregc485_cofins { get; set; }
        public DbSet<blococregc490> blococregc490 { get; set; }
        public DbSet<blococregc491_pis> blococregc491_pis { get; set; }
        public DbSet<blococregc495_cofins> blococregc495_cofins { get; set; }
        public DbSet<r05> r05 { get; set; }
        public DbSet<registro50entradas_agr> registro50entradas_agr { get; set; }
        public DbSet<registro50entradas_itens> registro50entradas_itens { get; set; }
        public DbSet<registro50saida_agr> registro50saida_agr { get; set; }
        public DbSet<registro50saidas_itens> registro50saidas_itens { get; set; }
        public DbSet<valoresinventario> valoresinventario { get; set; }
        public DbSet<restricoes> restricoes { get; set; }
    
        public virtual int AberturaDia()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AberturaDia");
        }
    
        public virtual int AjustarCamposNulos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AjustarCamposNulos");
        }
    
        public virtual int AjustarCamposNulosManual()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AjustarCamposNulosManual");
        }
    
        public virtual int AjustarTributos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AjustarTributos");
        }
    
        public virtual int AJusteRemovidos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AJusteRemovidos");
        }
    
        public virtual int arquivomorto()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("arquivomorto");
        }
    
        public virtual int AtualizarContRelGerencial()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AtualizarContRelGerencial");
        }
    
        public virtual int AtualizarDadosOff()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AtualizarDadosOff");
        }
    
        public virtual int BaixarCP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BaixarCP");
        }
    
        public virtual int ChecarIntegridadeCaixa()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ChecarIntegridadeCaixa");
        }
    
        public virtual int CriarInventario()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CriarInventario");
        }
    
        public virtual int CriarTabelasTemp()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CriarTabelasTemp");
        }
    
        public virtual int DescontoMaximo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DescontoMaximo");
        }
    
        public virtual int EncerrarCaixa()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EncerrarCaixa");
        }
    
        public virtual int EstornarBaixaCP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EstornarBaixaCP");
        }
    
        public virtual int EstornarDevolucao()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EstornarDevolucao");
        }
    
        public virtual int EstornarQuitacao()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EstornarQuitacao");
        }
    
        public virtual int ExcluirDocumento()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ExcluirDocumento");
        }
    
        public virtual int ExecutarApuracaoFiscal()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ExecutarApuracaoFiscal");
        }
    
        public virtual int FechamentoDiario()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FechamentoDiario");
        }
    
        public virtual int FinalizarDAV()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FinalizarDAV");
        }
    
        public virtual int FinalizarDAVOS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FinalizarDAVOS");
        }
    
        public virtual int FinalizarPreVenda()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FinalizarPreVenda");
        }
    
        public virtual int GerarDebitoServicos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GerarDebitoServicos");
        }
    
        public virtual int GerarNFe()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GerarNFe");
        }
    
        public virtual int GerarNumeroBoleto()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GerarNumeroBoleto");
        }
    
        public virtual int GravarR()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GravarR");
        }
    
        public virtual int ProcessarDAV()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ProcessarDAV");
        }
    
        public virtual int ProcessarDAVOS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ProcessarDAVOS");
        }
    
        public virtual int ProcessarDevolucao()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ProcessarDevolucao");
        }
    
        public virtual int ProcessarEntrada()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ProcessarEntrada");
        }
    
        public virtual int ProcessarPedidoCompra()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ProcessarPedidoCompra");
        }
    
        public virtual int ProcessarPreVenda()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ProcessarPreVenda");
        }
    
        public virtual int ProcessarTransferencia()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ProcessarTransferencia");
        }
    
        public virtual int QuitarDebitoCliente()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("QuitarDebitoCliente");
        }
    
        public virtual int QuitarDebitoClientePorValor()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("QuitarDebitoClientePorValor");
        }
    
        public virtual int recriarCodigoProduto()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("recriarCodigoProduto");
        }
    
        public virtual int resumoCaixas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("resumoCaixas");
        }
    
        public virtual int sp_gravaInfoGerencial()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_gravaInfoGerencial");
        }
    
        public virtual int zajustes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("zajustes");
        }
    
        public virtual int FinalizarVenda()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FinalizarVenda");
        }
    
        public virtual int AtualizarQdtRegistros()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AtualizarQdtRegistros");
        }
    
        public virtual int AtualizarDebitoCliente()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AtualizarDebitoCliente");
        }
    
        public virtual int ReservarPreVenda()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ReservarPreVenda");
        }
    
        public virtual int ApagaNFe()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ApagaNFe");
        }
    
        public virtual int AtualizarEstoqueOff()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AtualizarEstoqueOff");
        }
    
        public virtual int GerarDAV()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GerarDAV");
        }
    
        public virtual int ProdutosVendaarquivo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ProdutosVendaarquivo");
        }
    
        public virtual int QuitarDebitoClienteBoletos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("QuitarDebitoClienteBoletos");
        }
    
        public virtual int gerarLivroFiscal()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("gerarLivroFiscal");
        }
    
        public virtual int verificaVenda()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("verificaVenda");
        }
    
        public virtual int finalizarAv()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("finalizarAv");
        }
    
        public virtual int GravarCaixaSoma()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GravarCaixaSoma");
        }
    
        public virtual int fluxocaixa1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("fluxocaixa1");
        }
    }
}
