//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICEpdv
{
    using System;
    using System.Collections.Generic;
    
    public partial class vendedores
    {
        public int id { get; set; }
        public string codigo { get; set; }
        public string nome { get; set; }
        public string endereco { get; set; }
        public string bairro { get; set; }
        public string cidade { get; set; }
        public string cep { get; set; }
        public string estado { get; set; }
        public Nullable<decimal> cotamensal { get; set; }
        public Nullable<decimal> cotaqtdmensal { get; set; }
        public decimal a { get; set; }
        public decimal b { get; set; }
        public decimal c { get; set; }
        public decimal d { get; set; }
        public decimal e { get; set; }
        public decimal f { get; set; }
        public decimal g { get; set; }
        public decimal h { get; set; }
        public decimal i { get; set; }
        public decimal j { get; set; }
        public string CodigoFilial { get; set; }
        public string telefone { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public decimal dinheiro { get; set; }
        public decimal cartao { get; set; }
        public decimal cheque { get; set; }
        public decimal crediario { get; set; }
        public decimal devolucaorec { get; set; }
        public decimal devolucaovenda { get; set; }
        public decimal recebimento { get; set; }
        public string cpf { get; set; }
        public string cnpj { get; set; }
        public string rg { get; set; }
        public string telefone1 { get; set; }
        public string telefone2 { get; set; }
        public string email { get; set; }
        public string observacao { get; set; }
        public string inscricao { get; set; }
        public string ativo { get; set; }
        public string senha { get; set; }
        public decimal financeira { get; set; }
        public string categoria { get; set; }
    }
}
