//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICEpdv
{
    using System;
    using System.Collections.Generic;
    
    public partial class vendaarquivo
    {
        public Nullable<int> inc { get; set; }
        public string codigofilial { get; set; }
        public string operador { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public string codigo { get; set; }
        public string produto { get; set; }
        public decimal quantidade { get; set; }
        public Nullable<decimal> preco { get; set; }
        public Nullable<decimal> custo { get; set; }
        public decimal precooriginal { get; set; }
        public decimal Descontoperc { get; set; }
        public string id { get; set; }
        public decimal descontovalor { get; set; }
        public decimal total { get; set; }
        public string vendedor { get; set; }
        public int nrcontrole { get; set; }
        public long documento { get; set; }
        public string grupo { get; set; }
        public string subgrupo { get; set; }
        public string comissao { get; set; }
        public decimal ratdesc { get; set; }
        public decimal rateioencargos { get; set; }
        public string situacao { get; set; }
        public Nullable<decimal> customedio { get; set; }
        public string ecfnumero { get; set; }
        public string fornecedor { get; set; }
        public string fabricante { get; set; }
        public string NotaFiscal { get; set; }
        public int icms { get; set; }
        public string classe { get; set; }
        public string secao { get; set; }
        public string lote { get; set; }
        public string tributacao { get; set; }
        public string aentregar { get; set; }
        public decimal quantidadeanterior { get; set; }
        public decimal quantidadeatualizada { get; set; }
        public string codigofiscal { get; set; }
        public decimal customedioanterior { get; set; }
        public int codigocliente { get; set; }
        public int numerodevolucao { get; set; }
        public string codigobarras { get; set; }
        public int ipi { get; set; }
        public string unidade { get; set; }
        public int embalagem { get; set; }
        public string grade { get; set; }
        public string romaneio { get; set; }
        public string tipo { get; set; }
        public Nullable<decimal> cofins { get; set; }
        public Nullable<decimal> pis { get; set; }
        public decimal despesasacessorias { get; set; }
        public decimal percentualRedBaseCalcICMS { get; set; }
        public string serieNF { get; set; }
        public string cfop { get; set; }
        public decimal acrescimototalitem { get; set; }
        public string cstpis { get; set; }
        public string cstcofins { get; set; }
        public decimal icmsst { get; set; }
        public decimal percentualRedBaseCalcICMSST { get; set; }
        public decimal mvast { get; set; }
        public string subserienf { get; set; }
        public string modelodocfiscal { get; set; }
        public Nullable<decimal> aliquotaIPI { get; set; }
        public string ecffabricacao { get; set; }
        public string coo { get; set; }
        public string cancelado { get; set; }
        public string eaddados { get; set; }
        public string ccf { get; set; }
        public decimal pcredsn { get; set; }
        public decimal qUnidIPI { get; set; }
        public decimal vUnidIPI { get; set; }
        public string ncm { get; set; }
        public string nbm { get; set; }
        public string ncmespecie { get; set; }
        public decimal ratfrete { get; set; }
        public decimal ratseguro { get; set; }
        public decimal ratdespesas { get; set; }
        public string cstipi { get; set; }
        public string origem { get; set; }
        public Nullable<System.DateTime> datafabricacao { get; set; }
        public Nullable<System.DateTime> vencimentoproduto { get; set; }
        public string modalidadeDetBaseCalcICMS { get; set; }
        public string modalidadeDetBaseCalcICMSst { get; set; }
        public Nullable<int> idfornecedor { get; set; }
        public Nullable<System.DateTime> vencimento { get; set; }
        public Nullable<System.DateTime> dataalteracao { get; set; }
        public Nullable<System.TimeSpan> horaalteracao { get; set; }
        public string tipoalteracao { get; set; }
        public string itemDAV { get; set; }
        public string canceladoECF { get; set; }
        public string vendaatacado { get; set; }
        public decimal pautaICMS { get; set; }
        public decimal pautaICMSST { get; set; }
        public string cenqipi { get; set; }
        public string cest { get; set; }
        public string dpfinanceiro { get; set; }
        public Nullable<decimal> custogerencial { get; set; }
        public Nullable<decimal> vbcICMSST { get; set; }
        public Nullable<decimal> vICMSST { get; set; }
    }
}
