//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICEpdv
{
    using System;
    using System.Collections.Generic;
    
    public partial class web_noticias
    {
        public int id { get; set; }
        public string titulo { get; set; }
        public string noticia { get; set; }
        public string chamada { get; set; }
        public System.DateTime data { get; set; }
        public string autor { get; set; }
        public Nullable<System.TimeSpan> hora { get; set; }
        public string ver { get; set; }
    }
}
