//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICEpdv
{
    using System;
    using System.Collections.Generic;
    
    public partial class web_paginas_genericas
    {
        public int id { get; set; }
        public string chave_pagina { get; set; }
        public string titulo_pagina { get; set; }
        public string texto_pagina { get; set; }
        public string include_pagina { get; set; }
        public Nullable<System.DateTime> data_pagina { get; set; }
        public string autor_pagina { get; set; }
        public string botao_flash { get; set; }
    }
}
