//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICEpdv
{
    using System;
    using System.Collections.Generic;
    
    public partial class web_produtos_atualizacoes
    {
        public int id { get; set; }
        public string produto { get; set; }
        public string descricao { get; set; }
        public string versao { get; set; }
        public string caminho { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public Nullable<System.TimeSpan> hora { get; set; }
    }
}
