//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICEpdv
{
    using System;
    using System.Collections.Generic;
    
    public partial class web_downloads
    {
        public int id { get; set; }
        public string caminho { get; set; }
        public string arquivo { get; set; }
        public string descricao { get; set; }
        public string versao { get; set; }
        public string empresa { get; set; }
        public string os { get; set; }
        public System.DateTime data { get; set; }
        public string tipo { get; set; }
        public Nullable<System.TimeSpan> hora { get; set; }
        public string titulo { get; set; }
    }
}
