//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICEpdv
{
    using System;
    using System.Collections.Generic;
    
    public partial class webservicecontratos
    {
        public int id { get; set; }
        public string idfilial { get; set; }
        public Nullable<int> idcliente { get; set; }
        public string webservicecontrato { get; set; }
        public string nome { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public Nullable<System.DateTime> vencimentocontrato { get; set; }
        public string clientes { get; set; }
        public string produtos { get; set; }
        public string webservicecontratopreparo { get; set; }
    }
}
