//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICEpdv.ServiceReference2 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Clientes", Namespace="http://schemas.datacontract.org/2004/07/WCFSice")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SICEpdv.ServiceReference2.ClientesInfo))]
    public partial class Clientes : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cidadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int codigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string conjugeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dataCadastroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dataCobrancaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string estadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fantasiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string iqcardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string iqcardsuporteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string restritivaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sicemobileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sicewebField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string situacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string whatsappsuporteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cidade {
            get {
                return this.cidadeField;
            }
            set {
                if ((object.ReferenceEquals(this.cidadeField, value) != true)) {
                    this.cidadeField = value;
                    this.RaisePropertyChanged("cidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int codigo {
            get {
                return this.codigoField;
            }
            set {
                if ((this.codigoField.Equals(value) != true)) {
                    this.codigoField = value;
                    this.RaisePropertyChanged("codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string conjuge {
            get {
                return this.conjugeField;
            }
            set {
                if ((object.ReferenceEquals(this.conjugeField, value) != true)) {
                    this.conjugeField = value;
                    this.RaisePropertyChanged("conjuge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dataCadastro {
            get {
                return this.dataCadastroField;
            }
            set {
                if ((this.dataCadastroField.Equals(value) != true)) {
                    this.dataCadastroField = value;
                    this.RaisePropertyChanged("dataCadastro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dataCobranca {
            get {
                return this.dataCobrancaField;
            }
            set {
                if ((this.dataCobrancaField.Equals(value) != true)) {
                    this.dataCobrancaField = value;
                    this.RaisePropertyChanged("dataCobranca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                if ((object.ReferenceEquals(this.estadoField, value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fantasia {
            get {
                return this.fantasiaField;
            }
            set {
                if ((object.ReferenceEquals(this.fantasiaField, value) != true)) {
                    this.fantasiaField = value;
                    this.RaisePropertyChanged("fantasia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string iqcard {
            get {
                return this.iqcardField;
            }
            set {
                if ((object.ReferenceEquals(this.iqcardField, value) != true)) {
                    this.iqcardField = value;
                    this.RaisePropertyChanged("iqcard");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string iqcardsuporte {
            get {
                return this.iqcardsuporteField;
            }
            set {
                if ((object.ReferenceEquals(this.iqcardsuporteField, value) != true)) {
                    this.iqcardsuporteField = value;
                    this.RaisePropertyChanged("iqcardsuporte");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                if ((object.ReferenceEquals(this.nomeField, value) != true)) {
                    this.nomeField = value;
                    this.RaisePropertyChanged("nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string restritiva {
            get {
                return this.restritivaField;
            }
            set {
                if ((object.ReferenceEquals(this.restritivaField, value) != true)) {
                    this.restritivaField = value;
                    this.RaisePropertyChanged("restritiva");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sicemobile {
            get {
                return this.sicemobileField;
            }
            set {
                if ((object.ReferenceEquals(this.sicemobileField, value) != true)) {
                    this.sicemobileField = value;
                    this.RaisePropertyChanged("sicemobile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string siceweb {
            get {
                return this.sicewebField;
            }
            set {
                if ((object.ReferenceEquals(this.sicewebField, value) != true)) {
                    this.sicewebField = value;
                    this.RaisePropertyChanged("siceweb");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string situacao {
            get {
                return this.situacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.situacaoField, value) != true)) {
                    this.situacaoField = value;
                    this.RaisePropertyChanged("situacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tipo {
            get {
                return this.tipoField;
            }
            set {
                if ((object.ReferenceEquals(this.tipoField, value) != true)) {
                    this.tipoField = value;
                    this.RaisePropertyChanged("tipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string whatsappsuporte {
            get {
                return this.whatsappsuporteField;
            }
            set {
                if ((object.ReferenceEquals(this.whatsappsuporteField, value) != true)) {
                    this.whatsappsuporteField = value;
                    this.RaisePropertyChanged("whatsappsuporte");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientesInfo", Namespace="http://schemas.datacontract.org/2004/07/WCFSice")]
    [System.SerializableAttribute()]
    public partial class ClientesInfo : SICEpdv.ServiceReference2.Clientes {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string bairroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string celularField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cepField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cnpjField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cpfField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal creditoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal creditoCHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal debitoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string diretorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string enderecoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string faxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string filialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool inadimplenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string inscricaoEstadualField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool limiteUltrapassadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int mediaDiasPagamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime nascimentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string numeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string observacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string operadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int parcelasVencidasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal percAdimplenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int qtdChamadosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int qtdChequesDevField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int qtdComprasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int qtdParcelaAtrasadasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal saldoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal saldocomCHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string telefoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ultCompraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ultPagamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> valorContratoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal valorJurosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal valorMedioCupomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal valorReceberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal valorTotalField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string bairro {
            get {
                return this.bairroField;
            }
            set {
                if ((object.ReferenceEquals(this.bairroField, value) != true)) {
                    this.bairroField = value;
                    this.RaisePropertyChanged("bairro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string celular {
            get {
                return this.celularField;
            }
            set {
                if ((object.ReferenceEquals(this.celularField, value) != true)) {
                    this.celularField = value;
                    this.RaisePropertyChanged("celular");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cep {
            get {
                return this.cepField;
            }
            set {
                if ((object.ReferenceEquals(this.cepField, value) != true)) {
                    this.cepField = value;
                    this.RaisePropertyChanged("cep");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cnpj {
            get {
                return this.cnpjField;
            }
            set {
                if ((object.ReferenceEquals(this.cnpjField, value) != true)) {
                    this.cnpjField = value;
                    this.RaisePropertyChanged("cnpj");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cpf {
            get {
                return this.cpfField;
            }
            set {
                if ((object.ReferenceEquals(this.cpfField, value) != true)) {
                    this.cpfField = value;
                    this.RaisePropertyChanged("cpf");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal credito {
            get {
                return this.creditoField;
            }
            set {
                if ((this.creditoField.Equals(value) != true)) {
                    this.creditoField = value;
                    this.RaisePropertyChanged("credito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal creditoCH {
            get {
                return this.creditoCHField;
            }
            set {
                if ((this.creditoCHField.Equals(value) != true)) {
                    this.creditoCHField = value;
                    this.RaisePropertyChanged("creditoCH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal debito {
            get {
                return this.debitoField;
            }
            set {
                if ((this.debitoField.Equals(value) != true)) {
                    this.debitoField = value;
                    this.RaisePropertyChanged("debito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string diretor {
            get {
                return this.diretorField;
            }
            set {
                if ((object.ReferenceEquals(this.diretorField, value) != true)) {
                    this.diretorField = value;
                    this.RaisePropertyChanged("diretor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string endereco {
            get {
                return this.enderecoField;
            }
            set {
                if ((object.ReferenceEquals(this.enderecoField, value) != true)) {
                    this.enderecoField = value;
                    this.RaisePropertyChanged("endereco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fax {
            get {
                return this.faxField;
            }
            set {
                if ((object.ReferenceEquals(this.faxField, value) != true)) {
                    this.faxField = value;
                    this.RaisePropertyChanged("fax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string filial {
            get {
                return this.filialField;
            }
            set {
                if ((object.ReferenceEquals(this.filialField, value) != true)) {
                    this.filialField = value;
                    this.RaisePropertyChanged("filial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool inadimplente {
            get {
                return this.inadimplenteField;
            }
            set {
                if ((this.inadimplenteField.Equals(value) != true)) {
                    this.inadimplenteField = value;
                    this.RaisePropertyChanged("inadimplente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string inscricaoEstadual {
            get {
                return this.inscricaoEstadualField;
            }
            set {
                if ((object.ReferenceEquals(this.inscricaoEstadualField, value) != true)) {
                    this.inscricaoEstadualField = value;
                    this.RaisePropertyChanged("inscricaoEstadual");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool limiteUltrapassado {
            get {
                return this.limiteUltrapassadoField;
            }
            set {
                if ((this.limiteUltrapassadoField.Equals(value) != true)) {
                    this.limiteUltrapassadoField = value;
                    this.RaisePropertyChanged("limiteUltrapassado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int mediaDiasPagamento {
            get {
                return this.mediaDiasPagamentoField;
            }
            set {
                if ((this.mediaDiasPagamentoField.Equals(value) != true)) {
                    this.mediaDiasPagamentoField = value;
                    this.RaisePropertyChanged("mediaDiasPagamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime nascimento {
            get {
                return this.nascimentoField;
            }
            set {
                if ((this.nascimentoField.Equals(value) != true)) {
                    this.nascimentoField = value;
                    this.RaisePropertyChanged("nascimento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string numero {
            get {
                return this.numeroField;
            }
            set {
                if ((object.ReferenceEquals(this.numeroField, value) != true)) {
                    this.numeroField = value;
                    this.RaisePropertyChanged("numero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string observacao {
            get {
                return this.observacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.observacaoField, value) != true)) {
                    this.observacaoField = value;
                    this.RaisePropertyChanged("observacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string operador {
            get {
                return this.operadorField;
            }
            set {
                if ((object.ReferenceEquals(this.operadorField, value) != true)) {
                    this.operadorField = value;
                    this.RaisePropertyChanged("operador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int parcelasVencidas {
            get {
                return this.parcelasVencidasField;
            }
            set {
                if ((this.parcelasVencidasField.Equals(value) != true)) {
                    this.parcelasVencidasField = value;
                    this.RaisePropertyChanged("parcelasVencidas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal percAdimplencia {
            get {
                return this.percAdimplenciaField;
            }
            set {
                if ((this.percAdimplenciaField.Equals(value) != true)) {
                    this.percAdimplenciaField = value;
                    this.RaisePropertyChanged("percAdimplencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int qtdChamados {
            get {
                return this.qtdChamadosField;
            }
            set {
                if ((this.qtdChamadosField.Equals(value) != true)) {
                    this.qtdChamadosField = value;
                    this.RaisePropertyChanged("qtdChamados");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int qtdChequesDev {
            get {
                return this.qtdChequesDevField;
            }
            set {
                if ((this.qtdChequesDevField.Equals(value) != true)) {
                    this.qtdChequesDevField = value;
                    this.RaisePropertyChanged("qtdChequesDev");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int qtdCompras {
            get {
                return this.qtdComprasField;
            }
            set {
                if ((this.qtdComprasField.Equals(value) != true)) {
                    this.qtdComprasField = value;
                    this.RaisePropertyChanged("qtdCompras");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int qtdParcelaAtrasadas {
            get {
                return this.qtdParcelaAtrasadasField;
            }
            set {
                if ((this.qtdParcelaAtrasadasField.Equals(value) != true)) {
                    this.qtdParcelaAtrasadasField = value;
                    this.RaisePropertyChanged("qtdParcelaAtrasadas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal saldo {
            get {
                return this.saldoField;
            }
            set {
                if ((this.saldoField.Equals(value) != true)) {
                    this.saldoField = value;
                    this.RaisePropertyChanged("saldo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal saldocomCH {
            get {
                return this.saldocomCHField;
            }
            set {
                if ((this.saldocomCHField.Equals(value) != true)) {
                    this.saldocomCHField = value;
                    this.RaisePropertyChanged("saldocomCH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string telefone {
            get {
                return this.telefoneField;
            }
            set {
                if ((object.ReferenceEquals(this.telefoneField, value) != true)) {
                    this.telefoneField = value;
                    this.RaisePropertyChanged("telefone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ultCompra {
            get {
                return this.ultCompraField;
            }
            set {
                if ((this.ultCompraField.Equals(value) != true)) {
                    this.ultCompraField = value;
                    this.RaisePropertyChanged("ultCompra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ultPagamento {
            get {
                return this.ultPagamentoField;
            }
            set {
                if ((this.ultPagamentoField.Equals(value) != true)) {
                    this.ultPagamentoField = value;
                    this.RaisePropertyChanged("ultPagamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> valorContrato {
            get {
                return this.valorContratoField;
            }
            set {
                if ((this.valorContratoField.Equals(value) != true)) {
                    this.valorContratoField = value;
                    this.RaisePropertyChanged("valorContrato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal valorJuros {
            get {
                return this.valorJurosField;
            }
            set {
                if ((this.valorJurosField.Equals(value) != true)) {
                    this.valorJurosField = value;
                    this.RaisePropertyChanged("valorJuros");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal valorMedioCupom {
            get {
                return this.valorMedioCupomField;
            }
            set {
                if ((this.valorMedioCupomField.Equals(value) != true)) {
                    this.valorMedioCupomField = value;
                    this.RaisePropertyChanged("valorMedioCupom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal valorReceber {
            get {
                return this.valorReceberField;
            }
            set {
                if ((this.valorReceberField.Equals(value) != true)) {
                    this.valorReceberField = value;
                    this.RaisePropertyChanged("valorReceber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal valorTotal {
            get {
                return this.valorTotalField;
            }
            set {
                if ((this.valorTotalField.Equals(value) != true)) {
                    this.valorTotalField = value;
                    this.RaisePropertyChanged("valorTotal");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BoletoBancario", Namespace="http://schemas.datacontract.org/2004/07/WCFSice")]
    [System.SerializableAttribute()]
    public partial class BoletoBancario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CNPJSacadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string agenciaCedenteIMPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string bairroSacadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string bancoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string carteiraCedenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string carteiraCedenteIMPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cepSacadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cidadeSacadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codigoCedenteImpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string convenioCedenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dataDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dataVencimentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string documentoNumeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string enderecoSacadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string estadoSacadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int layoutBoletoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string localPagamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomeCedenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomeSacadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nossoNumeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string textoReciboSacado1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string textoReciboSacado2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal valorDescontoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal valorDocumentoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CNPJSacado {
            get {
                return this.CNPJSacadoField;
            }
            set {
                if ((object.ReferenceEquals(this.CNPJSacadoField, value) != true)) {
                    this.CNPJSacadoField = value;
                    this.RaisePropertyChanged("CNPJSacado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string agenciaCedenteIMP {
            get {
                return this.agenciaCedenteIMPField;
            }
            set {
                if ((object.ReferenceEquals(this.agenciaCedenteIMPField, value) != true)) {
                    this.agenciaCedenteIMPField = value;
                    this.RaisePropertyChanged("agenciaCedenteIMP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string bairroSacado {
            get {
                return this.bairroSacadoField;
            }
            set {
                if ((object.ReferenceEquals(this.bairroSacadoField, value) != true)) {
                    this.bairroSacadoField = value;
                    this.RaisePropertyChanged("bairroSacado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string banco {
            get {
                return this.bancoField;
            }
            set {
                if ((object.ReferenceEquals(this.bancoField, value) != true)) {
                    this.bancoField = value;
                    this.RaisePropertyChanged("banco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string carteiraCedente {
            get {
                return this.carteiraCedenteField;
            }
            set {
                if ((object.ReferenceEquals(this.carteiraCedenteField, value) != true)) {
                    this.carteiraCedenteField = value;
                    this.RaisePropertyChanged("carteiraCedente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string carteiraCedenteIMP {
            get {
                return this.carteiraCedenteIMPField;
            }
            set {
                if ((object.ReferenceEquals(this.carteiraCedenteIMPField, value) != true)) {
                    this.carteiraCedenteIMPField = value;
                    this.RaisePropertyChanged("carteiraCedenteIMP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cepSacado {
            get {
                return this.cepSacadoField;
            }
            set {
                if ((object.ReferenceEquals(this.cepSacadoField, value) != true)) {
                    this.cepSacadoField = value;
                    this.RaisePropertyChanged("cepSacado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cidadeSacado {
            get {
                return this.cidadeSacadoField;
            }
            set {
                if ((object.ReferenceEquals(this.cidadeSacadoField, value) != true)) {
                    this.cidadeSacadoField = value;
                    this.RaisePropertyChanged("cidadeSacado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codigoCedenteImp {
            get {
                return this.codigoCedenteImpField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoCedenteImpField, value) != true)) {
                    this.codigoCedenteImpField = value;
                    this.RaisePropertyChanged("codigoCedenteImp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string convenioCedente {
            get {
                return this.convenioCedenteField;
            }
            set {
                if ((object.ReferenceEquals(this.convenioCedenteField, value) != true)) {
                    this.convenioCedenteField = value;
                    this.RaisePropertyChanged("convenioCedente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dataDocumento {
            get {
                return this.dataDocumentoField;
            }
            set {
                if ((this.dataDocumentoField.Equals(value) != true)) {
                    this.dataDocumentoField = value;
                    this.RaisePropertyChanged("dataDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dataVencimento {
            get {
                return this.dataVencimentoField;
            }
            set {
                if ((this.dataVencimentoField.Equals(value) != true)) {
                    this.dataVencimentoField = value;
                    this.RaisePropertyChanged("dataVencimento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string documentoNumero {
            get {
                return this.documentoNumeroField;
            }
            set {
                if ((object.ReferenceEquals(this.documentoNumeroField, value) != true)) {
                    this.documentoNumeroField = value;
                    this.RaisePropertyChanged("documentoNumero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string enderecoSacado {
            get {
                return this.enderecoSacadoField;
            }
            set {
                if ((object.ReferenceEquals(this.enderecoSacadoField, value) != true)) {
                    this.enderecoSacadoField = value;
                    this.RaisePropertyChanged("enderecoSacado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string estadoSacado {
            get {
                return this.estadoSacadoField;
            }
            set {
                if ((object.ReferenceEquals(this.estadoSacadoField, value) != true)) {
                    this.estadoSacadoField = value;
                    this.RaisePropertyChanged("estadoSacado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int layoutBoleto {
            get {
                return this.layoutBoletoField;
            }
            set {
                if ((this.layoutBoletoField.Equals(value) != true)) {
                    this.layoutBoletoField = value;
                    this.RaisePropertyChanged("layoutBoleto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string localPagamento {
            get {
                return this.localPagamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.localPagamentoField, value) != true)) {
                    this.localPagamentoField = value;
                    this.RaisePropertyChanged("localPagamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nomeCedente {
            get {
                return this.nomeCedenteField;
            }
            set {
                if ((object.ReferenceEquals(this.nomeCedenteField, value) != true)) {
                    this.nomeCedenteField = value;
                    this.RaisePropertyChanged("nomeCedente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nomeSacado {
            get {
                return this.nomeSacadoField;
            }
            set {
                if ((object.ReferenceEquals(this.nomeSacadoField, value) != true)) {
                    this.nomeSacadoField = value;
                    this.RaisePropertyChanged("nomeSacado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nossoNumero {
            get {
                return this.nossoNumeroField;
            }
            set {
                if ((object.ReferenceEquals(this.nossoNumeroField, value) != true)) {
                    this.nossoNumeroField = value;
                    this.RaisePropertyChanged("nossoNumero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string textoReciboSacado1 {
            get {
                return this.textoReciboSacado1Field;
            }
            set {
                if ((object.ReferenceEquals(this.textoReciboSacado1Field, value) != true)) {
                    this.textoReciboSacado1Field = value;
                    this.RaisePropertyChanged("textoReciboSacado1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string textoReciboSacado2 {
            get {
                return this.textoReciboSacado2Field;
            }
            set {
                if ((object.ReferenceEquals(this.textoReciboSacado2Field, value) != true)) {
                    this.textoReciboSacado2Field = value;
                    this.RaisePropertyChanged("textoReciboSacado2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal valorDesconto {
            get {
                return this.valorDescontoField;
            }
            set {
                if ((this.valorDescontoField.Equals(value) != true)) {
                    this.valorDescontoField = value;
                    this.RaisePropertyChanged("valorDesconto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal valorDocumento {
            get {
                return this.valorDocumentoField;
            }
            set {
                if ((this.valorDocumentoField.Equals(value) != true)) {
                    this.valorDocumentoField = value;
                    this.RaisePropertyChanged("valorDocumento");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Extrato", Namespace="http://schemas.datacontract.org/2004/07/WCFSice")]
    [System.SerializableAttribute()]
    public partial class Extrato : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string filialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal jurosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string operadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal totalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal valorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime vencimentoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime data {
            get {
                return this.dataField;
            }
            set {
                if ((this.dataField.Equals(value) != true)) {
                    this.dataField = value;
                    this.RaisePropertyChanged("data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string filial {
            get {
                return this.filialField;
            }
            set {
                if ((object.ReferenceEquals(this.filialField, value) != true)) {
                    this.filialField = value;
                    this.RaisePropertyChanged("filial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idCliente {
            get {
                return this.idClienteField;
            }
            set {
                if ((this.idClienteField.Equals(value) != true)) {
                    this.idClienteField = value;
                    this.RaisePropertyChanged("idCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal juros {
            get {
                return this.jurosField;
            }
            set {
                if ((this.jurosField.Equals(value) != true)) {
                    this.jurosField = value;
                    this.RaisePropertyChanged("juros");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string operador {
            get {
                return this.operadorField;
            }
            set {
                if ((object.ReferenceEquals(this.operadorField, value) != true)) {
                    this.operadorField = value;
                    this.RaisePropertyChanged("operador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal total {
            get {
                return this.totalField;
            }
            set {
                if ((this.totalField.Equals(value) != true)) {
                    this.totalField = value;
                    this.RaisePropertyChanged("total");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal valor {
            get {
                return this.valorField;
            }
            set {
                if ((this.valorField.Equals(value) != true)) {
                    this.valorField = value;
                    this.RaisePropertyChanged("valor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime vencimento {
            get {
                return this.vencimentoField;
            }
            set {
                if ((this.vencimentoField.Equals(value) != true)) {
                    this.vencimentoField = value;
                    this.RaisePropertyChanged("vencimento");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResumoCrediario", Namespace="http://schemas.datacontract.org/2004/07/WCFSice")]
    [System.SerializableAttribute()]
    public partial class ResumoCrediario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal avencerCapitalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal avencerEncargosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal avencerFinanciadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal avencerJurosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal avencerTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal capitalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal encargosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal financiadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal jurosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal mediaParcelaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int parcelasAbertasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int parcelasVencidasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int prazoMedioPagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal totalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal vencidosCapitalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal vencidosCapitalate30Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal vencidosCapitalem30Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal vencidosCapitalmais90Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal vencidosEncargosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal vencidosEncargosate30Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal vencidosEncargosem30Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal vencidosEncargosmais90Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal vencidosFinanciadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal vencidosFinanciadoate30Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal vencidosFinanciadoem30Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal vencidosFinanciadomais90Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal vencidosJurosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal vencidosJurosate30Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal vencidosJurosem30Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal vencidosJurosmais90Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal vencidosTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal vencidosTotalate30Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal vencidosTotalem30Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal vencidosTotalmais90Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal avencerCapital {
            get {
                return this.avencerCapitalField;
            }
            set {
                if ((this.avencerCapitalField.Equals(value) != true)) {
                    this.avencerCapitalField = value;
                    this.RaisePropertyChanged("avencerCapital");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal avencerEncargos {
            get {
                return this.avencerEncargosField;
            }
            set {
                if ((this.avencerEncargosField.Equals(value) != true)) {
                    this.avencerEncargosField = value;
                    this.RaisePropertyChanged("avencerEncargos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal avencerFinanciado {
            get {
                return this.avencerFinanciadoField;
            }
            set {
                if ((this.avencerFinanciadoField.Equals(value) != true)) {
                    this.avencerFinanciadoField = value;
                    this.RaisePropertyChanged("avencerFinanciado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal avencerJuros {
            get {
                return this.avencerJurosField;
            }
            set {
                if ((this.avencerJurosField.Equals(value) != true)) {
                    this.avencerJurosField = value;
                    this.RaisePropertyChanged("avencerJuros");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal avencerTotal {
            get {
                return this.avencerTotalField;
            }
            set {
                if ((this.avencerTotalField.Equals(value) != true)) {
                    this.avencerTotalField = value;
                    this.RaisePropertyChanged("avencerTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal capital {
            get {
                return this.capitalField;
            }
            set {
                if ((this.capitalField.Equals(value) != true)) {
                    this.capitalField = value;
                    this.RaisePropertyChanged("capital");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal encargos {
            get {
                return this.encargosField;
            }
            set {
                if ((this.encargosField.Equals(value) != true)) {
                    this.encargosField = value;
                    this.RaisePropertyChanged("encargos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal financiado {
            get {
                return this.financiadoField;
            }
            set {
                if ((this.financiadoField.Equals(value) != true)) {
                    this.financiadoField = value;
                    this.RaisePropertyChanged("financiado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal juros {
            get {
                return this.jurosField;
            }
            set {
                if ((this.jurosField.Equals(value) != true)) {
                    this.jurosField = value;
                    this.RaisePropertyChanged("juros");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal mediaParcela {
            get {
                return this.mediaParcelaField;
            }
            set {
                if ((this.mediaParcelaField.Equals(value) != true)) {
                    this.mediaParcelaField = value;
                    this.RaisePropertyChanged("mediaParcela");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int parcelasAbertas {
            get {
                return this.parcelasAbertasField;
            }
            set {
                if ((this.parcelasAbertasField.Equals(value) != true)) {
                    this.parcelasAbertasField = value;
                    this.RaisePropertyChanged("parcelasAbertas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int parcelasVencidas {
            get {
                return this.parcelasVencidasField;
            }
            set {
                if ((this.parcelasVencidasField.Equals(value) != true)) {
                    this.parcelasVencidasField = value;
                    this.RaisePropertyChanged("parcelasVencidas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int prazoMedioPag {
            get {
                return this.prazoMedioPagField;
            }
            set {
                if ((this.prazoMedioPagField.Equals(value) != true)) {
                    this.prazoMedioPagField = value;
                    this.RaisePropertyChanged("prazoMedioPag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal total {
            get {
                return this.totalField;
            }
            set {
                if ((this.totalField.Equals(value) != true)) {
                    this.totalField = value;
                    this.RaisePropertyChanged("total");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal vencidosCapital {
            get {
                return this.vencidosCapitalField;
            }
            set {
                if ((this.vencidosCapitalField.Equals(value) != true)) {
                    this.vencidosCapitalField = value;
                    this.RaisePropertyChanged("vencidosCapital");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal vencidosCapitalate30 {
            get {
                return this.vencidosCapitalate30Field;
            }
            set {
                if ((this.vencidosCapitalate30Field.Equals(value) != true)) {
                    this.vencidosCapitalate30Field = value;
                    this.RaisePropertyChanged("vencidosCapitalate30");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal vencidosCapitalem30 {
            get {
                return this.vencidosCapitalem30Field;
            }
            set {
                if ((this.vencidosCapitalem30Field.Equals(value) != true)) {
                    this.vencidosCapitalem30Field = value;
                    this.RaisePropertyChanged("vencidosCapitalem30");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal vencidosCapitalmais90 {
            get {
                return this.vencidosCapitalmais90Field;
            }
            set {
                if ((this.vencidosCapitalmais90Field.Equals(value) != true)) {
                    this.vencidosCapitalmais90Field = value;
                    this.RaisePropertyChanged("vencidosCapitalmais90");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal vencidosEncargos {
            get {
                return this.vencidosEncargosField;
            }
            set {
                if ((this.vencidosEncargosField.Equals(value) != true)) {
                    this.vencidosEncargosField = value;
                    this.RaisePropertyChanged("vencidosEncargos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal vencidosEncargosate30 {
            get {
                return this.vencidosEncargosate30Field;
            }
            set {
                if ((this.vencidosEncargosate30Field.Equals(value) != true)) {
                    this.vencidosEncargosate30Field = value;
                    this.RaisePropertyChanged("vencidosEncargosate30");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal vencidosEncargosem30 {
            get {
                return this.vencidosEncargosem30Field;
            }
            set {
                if ((this.vencidosEncargosem30Field.Equals(value) != true)) {
                    this.vencidosEncargosem30Field = value;
                    this.RaisePropertyChanged("vencidosEncargosem30");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal vencidosEncargosmais90 {
            get {
                return this.vencidosEncargosmais90Field;
            }
            set {
                if ((this.vencidosEncargosmais90Field.Equals(value) != true)) {
                    this.vencidosEncargosmais90Field = value;
                    this.RaisePropertyChanged("vencidosEncargosmais90");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal vencidosFinanciado {
            get {
                return this.vencidosFinanciadoField;
            }
            set {
                if ((this.vencidosFinanciadoField.Equals(value) != true)) {
                    this.vencidosFinanciadoField = value;
                    this.RaisePropertyChanged("vencidosFinanciado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal vencidosFinanciadoate30 {
            get {
                return this.vencidosFinanciadoate30Field;
            }
            set {
                if ((this.vencidosFinanciadoate30Field.Equals(value) != true)) {
                    this.vencidosFinanciadoate30Field = value;
                    this.RaisePropertyChanged("vencidosFinanciadoate30");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal vencidosFinanciadoem30 {
            get {
                return this.vencidosFinanciadoem30Field;
            }
            set {
                if ((this.vencidosFinanciadoem30Field.Equals(value) != true)) {
                    this.vencidosFinanciadoem30Field = value;
                    this.RaisePropertyChanged("vencidosFinanciadoem30");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal vencidosFinanciadomais90 {
            get {
                return this.vencidosFinanciadomais90Field;
            }
            set {
                if ((this.vencidosFinanciadomais90Field.Equals(value) != true)) {
                    this.vencidosFinanciadomais90Field = value;
                    this.RaisePropertyChanged("vencidosFinanciadomais90");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal vencidosJuros {
            get {
                return this.vencidosJurosField;
            }
            set {
                if ((this.vencidosJurosField.Equals(value) != true)) {
                    this.vencidosJurosField = value;
                    this.RaisePropertyChanged("vencidosJuros");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal vencidosJurosate30 {
            get {
                return this.vencidosJurosate30Field;
            }
            set {
                if ((this.vencidosJurosate30Field.Equals(value) != true)) {
                    this.vencidosJurosate30Field = value;
                    this.RaisePropertyChanged("vencidosJurosate30");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal vencidosJurosem30 {
            get {
                return this.vencidosJurosem30Field;
            }
            set {
                if ((this.vencidosJurosem30Field.Equals(value) != true)) {
                    this.vencidosJurosem30Field = value;
                    this.RaisePropertyChanged("vencidosJurosem30");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal vencidosJurosmais90 {
            get {
                return this.vencidosJurosmais90Field;
            }
            set {
                if ((this.vencidosJurosmais90Field.Equals(value) != true)) {
                    this.vencidosJurosmais90Field = value;
                    this.RaisePropertyChanged("vencidosJurosmais90");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal vencidosTotal {
            get {
                return this.vencidosTotalField;
            }
            set {
                if ((this.vencidosTotalField.Equals(value) != true)) {
                    this.vencidosTotalField = value;
                    this.RaisePropertyChanged("vencidosTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal vencidosTotalate30 {
            get {
                return this.vencidosTotalate30Field;
            }
            set {
                if ((this.vencidosTotalate30Field.Equals(value) != true)) {
                    this.vencidosTotalate30Field = value;
                    this.RaisePropertyChanged("vencidosTotalate30");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal vencidosTotalem30 {
            get {
                return this.vencidosTotalem30Field;
            }
            set {
                if ((this.vencidosTotalem30Field.Equals(value) != true)) {
                    this.vencidosTotalem30Field = value;
                    this.RaisePropertyChanged("vencidosTotalem30");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal vencidosTotalmais90 {
            get {
                return this.vencidosTotalmais90Field;
            }
            set {
                if ((this.vencidosTotalmais90Field.Equals(value) != true)) {
                    this.vencidosTotalmais90Field = value;
                    this.RaisePropertyChanged("vencidosTotalmais90");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DadosInadimplencia", Namespace="http://schemas.datacontract.org/2004/07/WCFSice")]
    [System.SerializableAttribute()]
    public partial class DadosInadimplencia : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int anoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int mesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal percentualField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal valorGeradoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal valorRecebidoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ano {
            get {
                return this.anoField;
            }
            set {
                if ((this.anoField.Equals(value) != true)) {
                    this.anoField = value;
                    this.RaisePropertyChanged("ano");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descricao {
            get {
                return this.descricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.descricaoField, value) != true)) {
                    this.descricaoField = value;
                    this.RaisePropertyChanged("descricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int mes {
            get {
                return this.mesField;
            }
            set {
                if ((this.mesField.Equals(value) != true)) {
                    this.mesField = value;
                    this.RaisePropertyChanged("mes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal percentual {
            get {
                return this.percentualField;
            }
            set {
                if ((this.percentualField.Equals(value) != true)) {
                    this.percentualField = value;
                    this.RaisePropertyChanged("percentual");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal valorGerado {
            get {
                return this.valorGeradoField;
            }
            set {
                if ((this.valorGeradoField.Equals(value) != true)) {
                    this.valorGeradoField = value;
                    this.RaisePropertyChanged("valorGerado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal valorRecebido {
            get {
                return this.valorRecebidoField;
            }
            set {
                if ((this.valorRecebidoField.Equals(value) != true)) {
                    this.valorRecebidoField = value;
                    this.RaisePropertyChanged("valorRecebido");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.IWSClientes")]
    public interface IWSClientes {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSClientes/DataServidor", ReplyAction="http://tempuri.org/IWSClientes/DataServidorResponse")]
        System.DateTime DataServidor();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSClientes/QtdParcelasAtrasadas", ReplyAction="http://tempuri.org/IWSClientes/QtdParcelasAtrasadasResponse")]
        int QtdParcelasAtrasadas(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSClientes/DadosCliente", ReplyAction="http://tempuri.org/IWSClientes/DadosClienteResponse")]
        SICEpdv.ServiceReference2.Clientes DadosCliente(int idCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSClientes/CodigoCliente", ReplyAction="http://tempuri.org/IWSClientes/CodigoClienteResponse")]
        int CodigoCliente(string fantasia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSClientes/ListagemClientes", ReplyAction="http://tempuri.org/IWSClientes/ListagemClientesResponse")]
        SICEpdv.ServiceReference2.Clientes[] ListagemClientes(string credenciaisDB, string contrato, string pesquisa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSClientes/InfoCliente", ReplyAction="http://tempuri.org/IWSClientes/InfoClienteResponse")]
        SICEpdv.ServiceReference2.ClientesInfo InfoCliente(string credenciaisDB, string contrato, int idCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSClientes/Boletos", ReplyAction="http://tempuri.org/IWSClientes/BoletosResponse")]
        SICEpdv.ServiceReference2.BoletoBancario[] Boletos(string credenciaisDB, string contrato, int idCliente, string conta, string filial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSClientes/Extrato", ReplyAction="http://tempuri.org/IWSClientes/ExtratoResponse")]
        SICEpdv.ServiceReference2.Extrato[] Extrato(string credenciaisDB, string contrato, int idCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSClientes/PosicaoCrediario", ReplyAction="http://tempuri.org/IWSClientes/PosicaoCrediarioResponse")]
        SICEpdv.ServiceReference2.ResumoCrediario PosicaoCrediario(string credenciaisDB, string filial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSClientes/Inadimplencia", ReplyAction="http://tempuri.org/IWSClientes/InadimplenciaResponse")]
        SICEpdv.ServiceReference2.DadosInadimplencia[] Inadimplencia(string credenciaisDB, string filial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSClientes/EmailMensalidadeSICE", ReplyAction="http://tempuri.org/IWSClientes/EmailMensalidadeSICEResponse")]
        int EmailMensalidadeSICE(string assinatura, string complemento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSClientes/Versao", ReplyAction="http://tempuri.org/IWSClientes/VersaoResponse")]
        string Versao(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSClientes/ValorTotalDebitoCliente", ReplyAction="http://tempuri.org/IWSClientes/ValorTotalDebitoClienteResponse")]
        decimal ValorTotalDebitoCliente(string assinatura, int idCliente);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWSClientesChannel : SICEpdv.ServiceReference2.IWSClientes, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSClientesClient : System.ServiceModel.ClientBase<SICEpdv.ServiceReference2.IWSClientes>, SICEpdv.ServiceReference2.IWSClientes {
        
        public WSClientesClient() {
        }
        
        public WSClientesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSClientesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSClientesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSClientesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.DateTime DataServidor() {
            return base.Channel.DataServidor();
        }
        
        public int QtdParcelasAtrasadas(int value) {
            return base.Channel.QtdParcelasAtrasadas(value);
        }
        
        public SICEpdv.ServiceReference2.Clientes DadosCliente(int idCliente) {
            return base.Channel.DadosCliente(idCliente);
        }
        
        public int CodigoCliente(string fantasia) {
            return base.Channel.CodigoCliente(fantasia);
        }
        
        public SICEpdv.ServiceReference2.Clientes[] ListagemClientes(string credenciaisDB, string contrato, string pesquisa) {
            return base.Channel.ListagemClientes(credenciaisDB, contrato, pesquisa);
        }
        
        public SICEpdv.ServiceReference2.ClientesInfo InfoCliente(string credenciaisDB, string contrato, int idCliente) {
            return base.Channel.InfoCliente(credenciaisDB, contrato, idCliente);
        }
        
        public SICEpdv.ServiceReference2.BoletoBancario[] Boletos(string credenciaisDB, string contrato, int idCliente, string conta, string filial) {
            return base.Channel.Boletos(credenciaisDB, contrato, idCliente, conta, filial);
        }
        
        public SICEpdv.ServiceReference2.Extrato[] Extrato(string credenciaisDB, string contrato, int idCliente) {
            return base.Channel.Extrato(credenciaisDB, contrato, idCliente);
        }
        
        public SICEpdv.ServiceReference2.ResumoCrediario PosicaoCrediario(string credenciaisDB, string filial) {
            return base.Channel.PosicaoCrediario(credenciaisDB, filial);
        }
        
        public SICEpdv.ServiceReference2.DadosInadimplencia[] Inadimplencia(string credenciaisDB, string filial) {
            return base.Channel.Inadimplencia(credenciaisDB, filial);
        }
        
        public int EmailMensalidadeSICE(string assinatura, string complemento) {
            return base.Channel.EmailMensalidadeSICE(assinatura, complemento);
        }
        
        public string Versao(string id) {
            return base.Channel.Versao(id);
        }
        
        public decimal ValorTotalDebitoCliente(string assinatura, int idCliente) {
            return base.Channel.ValorTotalDebitoCliente(assinatura, idCliente);
        }
    }
}
